export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL';
export const ADD_EMPLOYEE_RESET = 'ADD_EMPLOYEE_RESET';

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL';
export const UPDATE_EMPLOYEE_RESET = 'UPDATE_EMPLOYEE_RESET';

export const REMOVE_EMPLOYEE_REQUEST = 'REMOVE_EMPLOYEE_REQUEST';
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS';
export const REMOVE_EMPLOYEE_FAIL = 'REMOVE_EMPLOYEE_FAIL';
export const REMOVE_EMPLOYEE_RESET = 'REMOVE_EMPLOYEE_RESET';

export const FETCH_ALL_EMPLOYEES_REQUEST =
  'FETCH_ALL_EMPLOYEES_REQUEST';
export const FETCH_ALL_EMPLOYEES_SUCCESS =
  'FETCH_ALL_EMPLOYEES_SUCCESS';
export const FETCH_ALL_EMPLOYEES_FAIL = 'FETCH_ALL_EMPLOYEES_FAIL';

export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAIL = 'FETCH_EMPLOYEE_FAIL';
