export const ADD_LEAVE_REQUEST_REQUEST = 'ADD_LEAVE_REQUEST_REQUEST';
export const ADD_LEAVE_REQUEST_SUCCESS = 'ADD_LEAVE_REQUEST_SUCCESS';
export const ADD_LEAVE_REQUEST_FAIL = 'ADD_LEAVE_REQUEST_FAIL';
export const ADD_LEAVE_REQUEST_RESET = 'ADD_LEAVE_REQUEST_RESET';

export const UPDATE_LEAVE_REQUEST_REQUEST =
  'UPDATE_LEAVE_REQUEST_REQUEST';
export const UPDATE_LEAVE_REQUEST_SUCCESS =
  'UPDATE_LEAVE_REQUEST_SUCCESS';
export const UPDATE_LEAVE_REQUEST_FAIL = 'UPDATE_LEAVE_REQUEST_FAIL';
export const UPDATE_LEAVE_REQUEST_RESET =
  'UPDATE_LEAVE_REQUEST_RESET';

export const APPROVE_LEAVE_REQUEST_REQUEST =
  'APPROVE_LEAVE_REQUEST_REQUEST';
export const APPROVE_LEAVE_REQUEST_SUCCESS =
  'APPROVE_LEAVE_REQUEST_SUCCESS';
export const APPROVE_LEAVE_REQUEST_FAIL =
  'APPROVE_LEAVE_REQUEST_FAIL';
export const APPROVE_LEAVE_REQUEST_RESET =
  'APPROVE_LEAVE_REQUEST_RESET';

export const REMOVE_LEAVE_REQUEST_REQUEST =
  'REMOVE_LEAVE_REQUEST_REQUEST';
export const REMOVE_LEAVE_REQUEST_SUCCESS =
  'REMOVE_LEAVE_REQUEST_SUCCESS';
export const REMOVE_LEAVE_REQUEST_FAIL = 'REMOVE_LEAVE_REQUEST_FAIL';
export const REMOVE_LEAVE_REQUEST_RESET =
  'REMOVE_LEAVE_REQUEST_RESET';

export const FETCH_ALL_LEAVE_REQUESTS_REQUEST =
  'FETCH_ALL_LEAVE_REQUESTS_REQUEST';
export const FETCH_ALL_LEAVE_REQUESTS_SUCCESS =
  'FETCH_ALL_LEAVE_REQUESTS_SUCCESS';
export const FETCH_ALL_LEAVE_REQUESTS_FAIL =
  'FETCH_ALL_LEAVE_REQUESTS_FAIL';

export const FETCH_MY_LEAVE_REQUESTS_REQUEST =
  'FETCH_MY_LEAVE_REQUESTS_REQUEST';
export const FETCH_MY_LEAVE_REQUESTS_SUCCESS =
  'FETCH_MY_LEAVE_REQUESTS_SUCCESS';
export const FETCH_MY_LEAVE_REQUESTS_FAIL =
  'FETCH_MY_LEAVE_REQUESTS_FAIL';

export const FETCH_LEAVE_REQUEST_REQUEST =
  'FETCH_LEAVE_REQUEST_REQUEST';
export const FETCH_LEAVE_REQUEST_SUCCESS =
  'FETCH_LEAVE_REQUEST_SUCCESS';
export const FETCH_LEAVE_REQUEST_FAIL = 'FETCH_LEAVE_REQUEST_FAIL';
