export const ADD_LEAVE_TYPE_REQUEST = 'ADD_LEAVE_TYPE_REQUEST';
export const ADD_LEAVE_TYPE_SUCCESS = 'ADD_LEAVE_TYPE_SUCCESS';
export const ADD_LEAVE_TYPE_FAIL = 'ADD_LEAVE_TYPE_FAIL';
export const ADD_LEAVE_TYPE_RESET = 'ADD_LEAVE_TYPE_RESET';

export const UPDATE_LEAVE_TYPE_REQUEST = 'UPDATE_LEAVE_TYPE_REQUEST';
export const UPDATE_LEAVE_TYPE_SUCCESS = 'UPDATE_LEAVE_TYPE_SUCCESS';
export const UPDATE_LEAVE_TYPE_FAIL = 'UPDATE_LEAVE_TYPE_FAIL';
export const UPDATE_LEAVE_TYPE_RESET = 'UPDATE_LEAVE_TYPE_RESET';

export const REMOVE_LEAVE_TYPE_REQUEST = 'REMOVE_LEAVE_TYPE_REQUEST';
export const REMOVE_LEAVE_TYPE_SUCCESS = 'REMOVE_LEAVE_TYPE_SUCCESS';
export const REMOVE_LEAVE_TYPE_FAIL = 'REMOVE_LEAVE_TYPE_FAIL';
export const REMOVE_LEAVE_TYPE_RESET = 'REMOVE_LEAVE_TYPE_RESET';

export const FETCH_ALL_LEAVE_TYPES_REQUEST =
  'FETCH_ALL_LEAVE_TYPES_REQUEST';
export const FETCH_ALL_LEAVE_TYPES_SUCCESS =
  'FETCH_ALL_LEAVE_TYPES_SUCCESS';
export const FETCH_ALL_LEAVE_TYPES_FAIL =
  'FETCH_ALL_LEAVE_TYPES_FAIL';

export const FETCH_LEAVE_TYPE_REQUEST = 'FETCH_LEAVE_TYPE_REQUEST';
export const FETCH_LEAVE_TYPE_SUCCESS = 'FETCH_LEAVE_TYPE_SUCCESS';
export const FETCH_LEAVE_TYPE_FAIL = 'FETCH_LEAVE_TYPE_FAIL';
